require("sewn_scripts/entities/familiar/upgrades/vanilla/brother_bobby")
require("sewn_scripts/entities/familiar/upgrades/vanilla/sister_maggy")
require("sewn_scripts/entities/familiar/upgrades/vanilla/ghost_baby")
require("sewn_scripts/entities/familiar/upgrades/vanilla/robo_baby")
require("sewn_scripts/entities/familiar/upgrades/vanilla/little_gish")
require("sewn_scripts/entities/familiar/upgrades/vanilla/seraphim")