require("sewn_scripts.items.trinkets.lost_button")
require("sewn_scripts.items.trinkets.contrasted_button")
require("sewn_scripts.items.trinkets.cracked_thimble")
require("sewn_scripts.items.trinkets.sewing_case")
require("sewn_scripts.items.trinkets.pin_cushion")
require("sewn_scripts.items.trinkets.thimble")