local AvailableFamiliarManager = require("sewn_scripts.core.available_familiars_manager")
local FamiliarDescription = require("sewn_scripts.mod_compat.eid.familiar_description")

local EncyclopediaUpgrades = { }

local autogeneratedItems = { }

-- Store the index of the "Upgrade" section for each collectibles which have an "Upgrade" section
local indexUpgradeSectionForCollectibleWiki = { }
-- Store all wiki items with their id as a key
local encyclopediaMap = nil

local function MapEncyclopedia()
    encyclopediaMap = { }
    if Encyclopedia == nil then return end
    for i, item in pairs(Encyclopedia["itemsTable"].all) do
        encyclopediaMap[item.ItemId] = item
    end
end

local function GenerateUnloadedWiki(collectibleID, data)
    EncyclopediaUpgrades:AddEncyclopediaUpgrade(data.FAMILIAR_ID, data.SUPER, data.ULTRA, data.NOTES)
end

if Encyclopedia then
    -- Override Encyclopedia.AutogenerateUnknownItems to add upgraded descriptions for generated items
    local OldAutogenerateUnknownItems = Encyclopedia.AutogenerateUnknownItems
    Encyclopedia.AutogenerateUnknownItems = function ()
        OldAutogenerateUnknownItems()
        MapEncyclopedia()
        for familiarCollectibleId, data in pairs(autogeneratedItems) do
            GenerateUnloadedWiki(familiarCollectibleId, data)
        end
    end
end

local function ToUpgrade(text, title)
    if Encyclopedia == nil or text == nil then return end
    local encyclopediaUpgrade = { }
    local encyclopediaText = Encyclopedia.EIDtoWiki(text, title)

    for i, data in pairs(encyclopediaText[1]) do
        if i == 1 then -- Title
            table.insert(encyclopediaUpgrade, {str = ""})
            table.insert(encyclopediaUpgrade, {str = data.str, fsize = data.fsize, clr = data.clr})
            table.insert(encyclopediaUpgrade, {str = ""})
        else -- Other lines
            for _, subtext in ipairs(Encyclopedia.fitTextToWidth(data.str, 1, 140)) do
                table.insert(encyclopediaUpgrade, {str = subtext, fsize = data.fsize, clr = data.clr, halign = data.halign})
            end
        end
    end

    return table.unpack({encyclopediaUpgrade})
end

local function GetEIDSuper(familiarID)
    local info = FamiliarDescription:GetInfoForFamiliar(familiarID)
    if info ~= nil then
        return info.SuperUpgrade
    end
    return ""
end
local function GetEIDUltra(familiarID)
    local info = FamiliarDescription:GetInfoForFamiliar(familiarID)
    if info ~= nil then
        return info.UltraUpgrade
    end
    return ""
end

function EncyclopediaUpgrades:AddEncyclopediaUpgrade(familiarID, superUpgradeText, ultraUpgradeText, notesUpgradeText, overrideWiki)
    if overrideWiki == nil then overrideWiki = true end
    local collectibleID = AvailableFamiliarManager:GetFamiliarCollectibleId(familiarID)

    if collectibleID == nil then
        return
    end
    
    if Encyclopedia == nil then
        return
    end

    if encyclopediaMap == nil then
        encyclopediaMap = {}
        MapEncyclopedia()
    end

    if encyclopediaMap[collectibleID] == nil then
        autogeneratedItems[collectibleID] = { FAMILIAR_ID = familiarID, SUPER = superUpgradeText, ULTRA = ultraUpgradeText, NOTES = notesUpgradeText }
        return
    end

    local wikiDesc = encyclopediaMap[collectibleID].WikiDesc
    
    if indexUpgradeSectionForCollectibleWiki[collectibleID] ~= nil then
        if overrideWiki == false then
            return
        end
        -- Remove the previous upgrade section
        wikiDesc[indexUpgradeSectionForCollectibleWiki[collectibleID]] = nil
        indexUpgradeSectionForCollectibleWiki[collectibleID] = nil
    end

    if superUpgradeText == nil then
        superUpgradeText = GetEIDSuper(familiarID)
    end
    if ultraUpgradeText == nil then
        ultraUpgradeText = GetEIDUltra(familiarID)
    end

    local _wikiUpgrade = { }
    local superWiki = ToUpgrade(superUpgradeText, "Super")
    local ultraWiki = ToUpgrade(ultraUpgradeText, "Ultra")
    local notesWiki = ToUpgrade(notesUpgradeText, "Notes") or {}

    -- Add the title "Upgrades"
    table.insert(_wikiUpgrade, {str = "Upgrades", fsize = 2, clr = 3, halign = 0})
    
    -- Add Super upgrade
    for i, data in pairs(superWiki) do
        table.insert(_wikiUpgrade, {str = data.str, fsize = data.fsize, clr = data.clr, halign = data.halign})
    end
    -- Add Ultra upgrade
    for i, data in pairs(ultraWiki) do
        table.insert(_wikiUpgrade, {str = data.str, fsize = data.fsize, clr = data.clr, halign = data.halign})
    end
    -- Add Notes upgrade
    for i, data in pairs(notesWiki) do
        table.insert(_wikiUpgrade, {str = data.str, fsize = data.fsize, clr = data.clr, halign = data.halign})
    end

    table.insert(wikiDesc, _wikiUpgrade)

    table.insert(_wikiUpgrade, {str="", fsize = 2})

    indexUpgradeSectionForCollectibleWiki[collectibleID] = #wikiDesc
end

return EncyclopediaUpgrades